import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { collection, addDoc, onSnapshot, doc, updateDoc, deleteDoc, serverTimestamp, getDoc, setDoc, writeBatch, deleteField } from "firebase/firestore";
import { db } from "../assets/firebase";
import { generateBracketMatches } from "../utils/bracketUtils";
import type { MatchWithId, MatchStatus, BracketWithId, BracketFormat, AgeGroup, WeightClass, Belt, TournamentSettings } from "../types";
import {
  AGE_GROUP_DURATIONS,
  AGE_GROUP_LABELS,
  AGE_GROUP_ORDER,
  WEIGHT_CLASSES,
  BELT_LABELS,
  BELT_COLORS,
  getBeltsForAgeGroup,
  getWeightClassLabel,
  DEFAULT_TOURNAMENT_SETTINGS,
} from "../types";
import { calculateMatTotalDuration } from "../utils/timeEstimates";

export default function AdminPanel() {
  const navigate = useNavigate();
  const [matches, setMatches] = useState<MatchWithId[]>([]);
  const [brackets, setBrackets] = useState<BracketWithId[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Tournament settings
  const [tournamentSettings, setTournamentSettings] = useState<TournamentSettings>(DEFAULT_TOURNAMENT_SETTINGS);
  const [showSettings, setShowSettings] = useState(false);

  // Tab state
  const [activeTab, setActiveTab] = useState<"brackets" | "matches" | "queues">("brackets");

  // Bracket form state
  const [showBracketForm, setShowBracketForm] = useState(false);
  const [bracketForm, setBracketForm] = useState({
    name: "",
    format: "double_elimination" as BracketFormat,
    matId: "mat1",
    ageGroup: "adult" as AgeGroup,
    weightClass: "middle" as WeightClass,
    belt: "white" as Belt,
    participants: ["", ""],
  });
  const [creatingBracket, setCreatingBracket] = useState(false);

  // Edit bracket state
  const [editingBracket, setEditingBracket] = useState<BracketWithId | null>(null);
  const [editForm, setEditForm] = useState({
    name: "",
    format: "double_elimination" as BracketFormat,
    matId: "mat1",
    ageGroup: "adult" as AgeGroup,
    weightClass: "middle" as WeightClass,
    belt: "white" as Belt,
  });
  const [savingEdit, setSavingEdit] = useState(false);

  // Auto-generate bracket name when age/weight/belt changes
  const autoGeneratedName = (() => {
    const ageLabel = AGE_GROUP_LABELS[bracketForm.ageGroup].split(" (")[0]; // Remove duration part
    const weightInfo = WEIGHT_CLASSES[bracketForm.ageGroup][bracketForm.weightClass];
    const weightLabel = weightInfo.maxKg ? `-${weightInfo.maxKg}kg` : "Open";
    const beltLabel = BELT_LABELS[bracketForm.belt];
    return `${ageLabel} / ${beltLabel} / ${weightLabel}`;
  })();

  // Match form state
  const [showMatchForm, setShowMatchForm] = useState(false);
  const [matchForm, setMatchForm] = useState({
    FighterAName: "",
    FighterBName: "",
    MatId: "mat1",
    Round: 1,
    PositionInRound: 1,
  });

  useEffect(() => {
    // Load tournament settings
    getDoc(doc(db, "settings", "tournament")).then((snap) => {
      if (snap.exists()) {
        setTournamentSettings(snap.data() as TournamentSettings);
      }
    });

    // Load matches
    const unsubMatches = onSnapshot(
      collection(db, "matches"),
      (snap) => {
        const data = snap.docs.map((d) => ({
          id: d.id,
          ...d.data(),
        } as MatchWithId));
        data.sort((a, b) => a.Round - b.Round || a.PositionInRound - b.PositionInRound);
        setMatches(data);
        setLoading(false);
      },
      (err) => {
        console.error("Error loading matches:", err);
        setError(err.message);
        setLoading(false);
      }
    );

    // Load brackets
    const unsubBrackets = onSnapshot(
      collection(db, "brackets"),
      (snap) => {
        const data = snap.docs.map((d) => ({
          id: d.id,
          ...d.data(),
        } as BracketWithId));
        setBrackets(data);
      },
      (err) => {
        console.error("Error loading brackets:", err);
      }
    );

    return () => {
      unsubMatches();
      unsubBrackets();
    };
  }, []);

  async function saveSettings(newSettings: TournamentSettings) {
    setTournamentSettings(newSettings);
    await setDoc(doc(db, "settings", "tournament"), newSettings);
  }

  // Bracket functions
  function addParticipant() {
    setBracketForm({ ...bracketForm, participants: [...bracketForm.participants, ""] });
  }

  function removeParticipant(index: number) {
    if (bracketForm.participants.length <= 2) return;
    const updated = bracketForm.participants.filter((_, i) => i !== index);
    setBracketForm({ ...bracketForm, participants: updated });
  }

  function updateParticipant(index: number, value: string) {
    const updated = [...bracketForm.participants];
    updated[index] = value;
    setBracketForm({ ...bracketForm, participants: updated });
  }

  async function createBracket(e: React.FormEvent) {
    e.preventDefault();
    setCreatingBracket(true);

    try {
      const validParticipants = bracketForm.participants.filter((p) => p.trim() !== "");
      if (validParticipants.length < 2) {
        alert("Need at least 2 participants");
        setCreatingBracket(false);
        return;
      }

      const matchDuration = AGE_GROUP_DURATIONS[bracketForm.ageGroup];
      const bracketName = bracketForm.name.trim() || autoGeneratedName;

      // Create bracket document
      const bracketRef = await addDoc(collection(db, "brackets"), {
        name: bracketName,
        format: bracketForm.format,
        participants: validParticipants,
        matId: bracketForm.matId,
        status: "active",
        createdAt: serverTimestamp(),
        ageGroup: bracketForm.ageGroup,
        weightClass: bracketForm.weightClass,
        belt: bracketForm.belt,
        matchDuration,
      });

      // Generate matches
      await generateBracketMatches(
        bracketForm.format,
        validParticipants,
        bracketRef.id,
        bracketForm.matId,
        matchDuration
      );

      // Reset form
      setBracketForm({
        name: "",
        format: "double_elimination",
        matId: "mat1",
        ageGroup: "adult",
        weightClass: "middle",
        belt: "white",
        participants: ["", ""],
      });
      setShowBracketForm(false);
    } catch (err) {
      console.error("Error creating bracket:", err);
      alert("Error creating bracket");
    } finally {
      setCreatingBracket(false);
    }
  }

  async function deleteBracket(bracketId: string) {
    if (!confirm("Delete this bracket and all its matches?")) return;

    // Delete all matches in bracket
    const bracketMatches = matches.filter((m) => m.bracketId === bracketId);
    for (const match of bracketMatches) {
      await deleteDoc(doc(db, "matches", match.id));
    }

    // Delete bracket
    await deleteDoc(doc(db, "brackets", bracketId));
  }

  function startEditBracket(bracket: BracketWithId) {
    setEditingBracket(bracket);
    setEditForm({
      name: bracket.name,
      format: bracket.format,
      matId: bracket.matId,
      ageGroup: bracket.ageGroup,
      weightClass: bracket.weightClass,
      belt: bracket.belt,
    });
  }

  async function saveEditBracket(e: React.FormEvent) {
    e.preventDefault();
    if (!editingBracket) return;

    const formatChanged = editForm.format !== editingBracket.format;

    // Warn if format is changing - this will delete all matches
    if (formatChanged) {
      const hasFinishedMatches = matches.some(
        (m) => m.bracketId === editingBracket.id && m.Status === "finished"
      );
      if (hasFinishedMatches) {
        if (!confirm("Changing the format will DELETE ALL MATCHES including finished ones. Are you sure?")) {
          return;
        }
      }
    }

    setSavingEdit(true);
    try {
      const newMatchDuration = AGE_GROUP_DURATIONS[editForm.ageGroup];

      // Update bracket
      await updateDoc(doc(db, "brackets", editingBracket.id), {
        name: editForm.name,
        format: editForm.format,
        matId: editForm.matId,
        ageGroup: editForm.ageGroup,
        weightClass: editForm.weightClass,
        belt: editForm.belt,
        matchDuration: newMatchDuration,
      });

      const bracketMatches = matches.filter((m) => m.bracketId === editingBracket.id);

      if (formatChanged) {
        // Delete all existing matches
        for (const match of bracketMatches) {
          await deleteDoc(doc(db, "matches", match.id));
        }

        // Regenerate matches with new format
        await generateBracketMatches(
          editForm.format,
          editingBracket.participants,
          editingBracket.id,
          editForm.matId,
          newMatchDuration
        );
      } else {
        // Just update mat and duration on existing matches
        for (const match of bracketMatches) {
          await updateDoc(doc(db, "matches", match.id), {
            MatId: editForm.matId,
            matchDuration: newMatchDuration,
          });
        }
      }

      setEditingBracket(null);
    } catch (err) {
      console.error("Error updating bracket:", err);
      alert("Error updating bracket");
    } finally {
      setSavingEdit(false);
    }
  }

  // Match functions
  async function createMatch(e: React.FormEvent) {
    e.preventDefault();
    await addDoc(collection(db, "matches"), {
      ...matchForm,
      Status: "scheduled" as MatchStatus,
      PointsA: 0,
      PointsB: 0,
      AdvantagesA: 0,
      AdvantagesB: 0,
      PenaltiesA: 0,
      PenaltiesB: 0,
    });
    setMatchForm({
      FighterAName: "",
      FighterBName: "",
      MatId: "mat1",
      Round: 1,
      PositionInRound: 1,
    });
    setShowMatchForm(false);
  }

  async function updateMatchStatus(matchId: string, status: MatchStatus) {
    await updateDoc(doc(db, "matches", matchId), { Status: status });
  }

  async function deleteMatch(matchId: string) {
    if (!confirm("Delete this match?")) return;
    await deleteDoc(doc(db, "matches", matchId));
  }

  async function updateMatchMat(matchId: string, matId: string) {
    await updateDoc(doc(db, "matches", matchId), { MatId: matId });
  }

  // Reorder matches in queue
  async function reorderMatches(reorderedMatches: MatchWithId[]) {
    const batch = writeBatch(db);
    reorderedMatches.forEach((match, index) => {
      const ref = doc(db, "matches", match.id);
      batch.update(ref, { queueOrder: index });
    });
    await batch.commit();
  }

  // Reset queue order for a mat (back to automatic ordering)
  async function resetQueueOrder(matId: string) {
    if (!confirm("Reset queue to automatic ordering (by age group)?")) return;

    // Reset ALL matches on this mat (remove queueOrder field entirely)
    const matMatches = matches.filter((m) => m.MatId === matId && m.Status !== "finished");
    if (matMatches.length === 0) return;

    const batch = writeBatch(db);
    matMatches.forEach((match) => {
      const ref = doc(db, "matches", match.id);
      batch.update(ref, { queueOrder: deleteField() });
    });
    await batch.commit();

    alert("Queue reset to automatic age-group ordering!");
  }

  if (loading) return <div style={{ padding: 40 }}>Loading...</div>;
  if (error) return <div style={{ color: "crimson", padding: 40 }}>Error: {error}</div>;

  const standaloneMatches = matches.filter((m) => !m.bracketId);

  return (
    <div style={{ maxWidth: 1200, margin: "0 auto", padding: 20 }}>
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
        <h1 style={{ margin: 0 }}>Admin Panel</h1>
        <button
          onClick={() => setShowSettings(!showSettings)}
          style={{ padding: "8px 16px", background: showSettings ? "#0d6efd" : "#333" }}
        >
          Tournament Settings
        </button>
      </header>

      {/* Tournament Settings Panel */}
      {showSettings && (
        <div style={{ background: "#1a1a1a", padding: 20, borderRadius: 8, marginBottom: 24 }}>
          <h3 style={{ margin: "0 0 16px 0" }}>Tournament Settings</h3>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16 }}>
            <label style={{ display: "grid", gap: 4 }}>
              Start Time
              <input
                type="time"
                value={tournamentSettings.startTime}
                onChange={(e) => saveSettings({ ...tournamentSettings, startTime: e.target.value })}
                style={{ padding: "8px 12px" }}
              />
            </label>

            <label style={{ display: "grid", gap: 4 }}>
              Buffer Between Matches (min)
              <input
                type="number"
                min={0}
                max={10}
                value={tournamentSettings.bufferMinutes}
                onChange={(e) => saveSettings({ ...tournamentSettings, bufferMinutes: parseInt(e.target.value) || 0 })}
                style={{ padding: "8px 12px" }}
              />
            </label>

            <div style={{ display: "grid", gap: 4 }}>
              <span style={{ color: "#888", fontSize: "0.875rem" }}>Estimated Duration</span>
              <div style={{ display: "grid", gap: 4, fontSize: "0.875rem" }}>
                {["mat1", "mat2", "mat3", "mat4"].map((matId) => {
                  const { totalMinutes, matchCount } = calculateMatTotalDuration(matches, matId, tournamentSettings);
                  if (matchCount === 0) return null;
                  return (
                    <div key={matId} style={{ display: "flex", justifyContent: "space-between" }}>
                      <span>{matId.replace("mat", "Mat ")}</span>
                      <span style={{ color: "#888" }}>
                        {matchCount} matches / ~{Math.floor(totalMinutes / 60)}h {totalMinutes % 60}m
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tabs */}
      <div style={{ display: "flex", gap: 8, marginBottom: 24 }}>
        <button
          onClick={() => setActiveTab("brackets")}
          style={{
            padding: "12px 24px",
            background: activeTab === "brackets" ? "#0d6efd" : "#333",
            color: "white",
            border: "none",
            borderRadius: 4,
            cursor: "pointer",
            fontWeight: activeTab === "brackets" ? 700 : 400,
          }}
        >
          Brackets ({brackets.length})
        </button>
        <button
          onClick={() => setActiveTab("matches")}
          style={{
            padding: "12px 24px",
            background: activeTab === "matches" ? "#0d6efd" : "#333",
            color: "white",
            border: "none",
            borderRadius: 4,
            cursor: "pointer",
            fontWeight: activeTab === "matches" ? 700 : 400,
          }}
        >
          Standalone Matches ({standaloneMatches.length})
        </button>
        <button
          onClick={() => setActiveTab("queues")}
          style={{
            padding: "12px 24px",
            background: activeTab === "queues" ? "#0d6efd" : "#333",
            color: "white",
            border: "none",
            borderRadius: 4,
            cursor: "pointer",
            fontWeight: activeTab === "queues" ? 700 : 400,
          }}
        >
          Mat Queues
        </button>
      </div>

      {/* Brackets Tab */}
      {activeTab === "brackets" && (
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
            <h2 style={{ margin: 0 }}>Brackets</h2>
            <button onClick={() => setShowBracketForm(!showBracketForm)}>
              {showBracketForm ? "Cancel" : "Create Bracket"}
            </button>
          </div>

          {showBracketForm && (
            <form onSubmit={createBracket} style={{ background: "#1a1a1a", padding: 20, borderRadius: 8, marginBottom: 24 }}>
              <h3 style={{ margin: "0 0 16px 0" }}>New Bracket</h3>

              <div style={{ display: "grid", gap: 16 }}>
                {/* Age / Belt / Weight row */}
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
                  <label style={{ display: "grid", gap: 4 }}>
                    Age Group
                    <select
                      value={bracketForm.ageGroup}
                      onChange={(e) => {
                        const newAge = e.target.value as AgeGroup;
                        const availableBelts = getBeltsForAgeGroup(newAge);
                        const newBelt = availableBelts.includes(bracketForm.belt as Belt)
                          ? bracketForm.belt
                          : availableBelts[0];
                        setBracketForm({ ...bracketForm, ageGroup: newAge, belt: newBelt });
                      }}
                    >
                      {(Object.keys(AGE_GROUP_LABELS) as AgeGroup[]).map((ag) => (
                        <option key={ag} value={ag}>{AGE_GROUP_LABELS[ag]}</option>
                      ))}
                    </select>
                  </label>

                  <label style={{ display: "grid", gap: 4 }}>
                    Belt
                    <select
                      value={bracketForm.belt}
                      onChange={(e) => setBracketForm({ ...bracketForm, belt: e.target.value as Belt })}
                      style={{
                        borderLeft: `4px solid ${BELT_COLORS[bracketForm.belt]}`,
                      }}
                    >
                      {getBeltsForAgeGroup(bracketForm.ageGroup).map((belt) => (
                        <option key={belt} value={belt}>{BELT_LABELS[belt]}</option>
                      ))}
                    </select>
                  </label>

                  <label style={{ display: "grid", gap: 4 }}>
                    Weight Class
                    <select
                      value={bracketForm.weightClass}
                      onChange={(e) => setBracketForm({ ...bracketForm, weightClass: e.target.value as WeightClass })}
                    >
                      {(Object.keys(WEIGHT_CLASSES[bracketForm.ageGroup]) as WeightClass[]).map((wc) => (
                        <option key={wc} value={wc}>
                          {getWeightClassLabel(bracketForm.ageGroup, wc)}
                        </option>
                      ))}
                    </select>
                  </label>
                </div>

                {/* Auto-generated name preview */}
                <div style={{ background: "#2a2a2a", padding: "12px 16px", borderRadius: 6 }}>
                  <div style={{ fontSize: "0.75rem", color: "#888", marginBottom: 4 }}>Bracket Name (auto-generated)</div>
                  <div style={{ fontWeight: 600, fontSize: "1.1rem" }}>{autoGeneratedName}</div>
                </div>

                <label style={{ display: "grid", gap: 4 }}>
                  Custom Name (optional)
                  <input
                    type="text"
                    value={bracketForm.name}
                    onChange={(e) => setBracketForm({ ...bracketForm, name: e.target.value })}
                    placeholder="Leave empty to use auto-generated name"
                  />
                </label>

                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                  <label style={{ display: "grid", gap: 4 }}>
                    Format
                    <select
                      value={bracketForm.format}
                      onChange={(e) => setBracketForm({ ...bracketForm, format: e.target.value as BracketFormat })}
                    >
                      <option value="double_elimination">Double Elimination</option>
                      <option value="round_robin">Round Robin</option>
                    </select>
                  </label>

                  <label style={{ display: "grid", gap: 4 }}>
                    Mat
                    <select
                      value={bracketForm.matId}
                      onChange={(e) => setBracketForm({ ...bracketForm, matId: e.target.value })}
                    >
                      <option value="mat1">Mat 1</option>
                      <option value="mat2">Mat 2</option>
                      <option value="mat3">Mat 3</option>
                      <option value="mat4">Mat 4</option>
                    </select>
                  </label>
                </div>

                <div>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
                    <label style={{ fontWeight: 600 }}>Participants</label>
                    <button type="button" onClick={addParticipant} style={{ padding: "4px 12px" }}>
                      + Add
                    </button>
                  </div>
                  <div style={{ display: "grid", gap: 8 }}>
                    {bracketForm.participants.map((p, i) => (
                      <div key={i} style={{ display: "flex", gap: 8 }}>
                        <input
                          type="text"
                          value={p}
                          onChange={(e) => updateParticipant(i, e.target.value)}
                          placeholder={`Fighter ${i + 1}`}
                          style={{ flex: 1 }}
                        />
                        {bracketForm.participants.length > 2 && (
                          <button type="button" onClick={() => removeParticipant(i)} style={{ padding: "4px 12px" }}>
                            X
                          </button>
                        )}
                      </div>
                    ))}
                  </div>
                </div>

                <button type="submit" disabled={creatingBracket} style={{ padding: "12px", fontWeight: 600 }}>
                  {creatingBracket ? "Creating..." : "Create Bracket"}
                </button>
              </div>
            </form>
          )}

          {/* Edit Bracket Modal */}
          {editingBracket && (
            <div
              style={{
                position: "fixed",
                inset: 0,
                background: "rgba(0,0,0,0.8)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                zIndex: 1000,
                padding: 20,
                overflow: "auto",
              }}
              onClick={() => setEditingBracket(null)}
            >
              <form
                onSubmit={saveEditBracket}
                style={{
                  background: "#1a1a1a",
                  padding: 32,
                  borderRadius: 12,
                  maxWidth: 700,
                  width: "100%",
                  margin: "auto",
                }}
                onClick={(e) => e.stopPropagation()}
              >
                <h2 style={{ margin: "0 0 20px 0" }}>Edit Bracket</h2>

                <div style={{ display: "grid", gap: 16 }}>
                  <label style={{ display: "grid", gap: 4 }}>
                    Bracket Name
                    <input
                      type="text"
                      value={editForm.name}
                      onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                      required
                    />
                  </label>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                    <label style={{ display: "grid", gap: 4 }}>
                      Format
                      <select
                        value={editForm.format}
                        onChange={(e) => setEditForm({ ...editForm, format: e.target.value as BracketFormat })}
                      >
                        <option value="double_elimination">Double Elimination</option>
                        <option value="round_robin">Round Robin</option>
                      </select>
                    </label>

                    <label style={{ display: "grid", gap: 4 }}>
                      Mat
                      <select
                        value={editForm.matId}
                        onChange={(e) => setEditForm({ ...editForm, matId: e.target.value })}
                      >
                        <option value="mat1">Mat 1</option>
                        <option value="mat2">Mat 2</option>
                        <option value="mat3">Mat 3</option>
                        <option value="mat4">Mat 4</option>
                      </select>
                    </label>
                  </div>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}>
                    <label style={{ display: "grid", gap: 4 }}>
                      Age Group
                      <select
                        value={editForm.ageGroup}
                        onChange={(e) => {
                          const newAge = e.target.value as AgeGroup;
                          const availableBelts = getBeltsForAgeGroup(newAge);
                          const newBelt = availableBelts.includes(editForm.belt as Belt)
                            ? editForm.belt
                            : availableBelts[0];
                          setEditForm({ ...editForm, ageGroup: newAge, belt: newBelt });
                        }}
                      >
                        {(Object.keys(AGE_GROUP_LABELS) as AgeGroup[]).map((ag) => (
                          <option key={ag} value={ag}>{AGE_GROUP_LABELS[ag]}</option>
                        ))}
                      </select>
                    </label>

                    <label style={{ display: "grid", gap: 4 }}>
                      Belt
                      <select
                        value={editForm.belt}
                        onChange={(e) => setEditForm({ ...editForm, belt: e.target.value as Belt })}
                        style={{ borderLeft: `4px solid ${BELT_COLORS[editForm.belt]}` }}
                      >
                        {getBeltsForAgeGroup(editForm.ageGroup).map((belt) => (
                          <option key={belt} value={belt}>{BELT_LABELS[belt]}</option>
                        ))}
                      </select>
                    </label>

                    <label style={{ display: "grid", gap: 4 }}>
                      Weight Class
                      <select
                        value={editForm.weightClass}
                        onChange={(e) => setEditForm({ ...editForm, weightClass: e.target.value as WeightClass })}
                      >
                        {(Object.keys(WEIGHT_CLASSES[editForm.ageGroup]) as WeightClass[]).map((wc) => (
                          <option key={wc} value={wc}>
                            {getWeightClassLabel(editForm.ageGroup, wc)}
                          </option>
                        ))}
                      </select>
                    </label>
                  </div>

                  <div style={{ background: "#2a2a2a", padding: 12, borderRadius: 6, fontSize: "0.875rem", color: "#888" }}>
                    Match duration: {Math.floor(AGE_GROUP_DURATIONS[editForm.ageGroup] / 60)} min (based on age group).
                    {editingBracket && editForm.format !== editingBracket.format && (
                      <div style={{ color: "#ffc107", marginTop: 8 }}>
                        Warning: Changing format will delete all matches and regenerate them!
                      </div>
                    )}
                  </div>

                  <div style={{ display: "flex", gap: 12, marginTop: 8 }}>
                    <button
                      type="button"
                      onClick={() => setEditingBracket(null)}
                      style={{ flex: 1, padding: "12px", background: "#333" }}
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={savingEdit}
                      style={{ flex: 1, padding: "12px", background: "#0d6efd", fontWeight: 600 }}
                    >
                      {savingEdit ? "Saving..." : "Save Changes"}
                    </button>
                  </div>
                </div>
              </form>
            </div>
          )}

          {/* Bracket List */}
          <div style={{ display: "grid", gap: 12 }}>
            {[...brackets].sort((a, b) => {
              // First sort by mat
              const matCompare = a.matId.localeCompare(b.matId);
              if (matCompare !== 0) return matCompare;
              // Then by age group (youngest first)
              const ageOrder = AGE_GROUP_ORDER;
              return ageOrder.indexOf(a.ageGroup) - ageOrder.indexOf(b.ageGroup);
            }).map((bracket) => {
              const bracketMatches = matches.filter((m) => m.bracketId === bracket.id);
              const finishedMatches = bracketMatches.filter((m) => m.Status === "finished").length;
              const totalMatches = bracketMatches.length;
              const beltColor = bracket.belt ? BELT_COLORS[bracket.belt] : "#666";

              return (
                <div
                  key={bracket.id}
                  style={{
                    background: "#1a1a1a",
                    padding: 16,
                    borderRadius: 8,
                    display: "grid",
                    gridTemplateColumns: "1fr auto auto auto auto",
                    gap: 16,
                    alignItems: "center",
                    borderLeft: `4px solid ${beltColor}`,
                  }}
                >
                  <div>
                    <div style={{ fontWeight: 700, fontSize: "1.1rem" }}>{bracket.name}</div>
                    <div style={{ fontSize: "0.875rem", color: "#888", marginTop: 4 }}>
                      {bracket.format === "double_elimination" ? "Double Elim" : "Round Robin"} •{" "}
                      {bracket.participants.length} fighters • {finishedMatches}/{totalMatches} matches •{" "}
                      {Math.floor((bracket.matchDuration || 300) / 60)} min
                    </div>
                  </div>

                  <div style={{ fontSize: "0.875rem", color: "#888" }}>
                    {bracket.matId.replace("mat", "Mat ")}
                  </div>

                  <button
                    onClick={() => startEditBracket(bracket)}
                    style={{ padding: "8px 16px", background: "#6c757d", color: "white" }}
                  >
                    Edit
                  </button>

                  <button
                    onClick={() => navigate(`/bracket/${bracket.id}`)}
                    style={{ padding: "8px 16px" }}
                  >
                    View Bracket
                  </button>

                  <button
                    onClick={() => deleteBracket(bracket.id)}
                    style={{ padding: "8px 16px", background: "#dc3545", color: "white" }}
                  >
                    Delete
                  </button>
                </div>
              );
            })}

            {brackets.length === 0 && (
              <div style={{ textAlign: "center", padding: 40, color: "#888" }}>
                No brackets yet. Create one to get started!
              </div>
            )}
          </div>
        </div>
      )}

      {/* Matches Tab */}
      {activeTab === "matches" && (
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
            <h2 style={{ margin: 0 }}>Standalone Matches</h2>
            <button onClick={() => setShowMatchForm(!showMatchForm)}>
              {showMatchForm ? "Cancel" : "Create Match"}
            </button>
          </div>

          {showMatchForm && (
            <form onSubmit={createMatch} style={{ background: "#1a1a1a", padding: 20, borderRadius: 8, marginBottom: 24 }}>
              <h3 style={{ margin: "0 0 16px 0" }}>New Match</h3>

              <div style={{ display: "grid", gap: 12 }}>
                <label style={{ display: "grid", gap: 4 }}>
                  Fighter A Name
                  <input
                    type="text"
                    value={matchForm.FighterAName}
                    onChange={(e) => setMatchForm({ ...matchForm, FighterAName: e.target.value })}
                    required
                  />
                </label>

                <label style={{ display: "grid", gap: 4 }}>
                  Fighter B Name
                  <input
                    type="text"
                    value={matchForm.FighterBName}
                    onChange={(e) => setMatchForm({ ...matchForm, FighterBName: e.target.value })}
                    required
                  />
                </label>

                <label style={{ display: "grid", gap: 4 }}>
                  Mat
                  <select
                    value={matchForm.MatId}
                    onChange={(e) => setMatchForm({ ...matchForm, MatId: e.target.value })}
                  >
                    <option value="mat1">Mat 1</option>
                    <option value="mat2">Mat 2</option>
                    <option value="mat3">Mat 3</option>
                    <option value="mat4">Mat 4</option>
                  </select>
                </label>

                <button type="submit">Create Match</button>
              </div>
            </form>
          )}

          {/* Match List */}
          <div style={{ display: "grid", gap: 8 }}>
            {standaloneMatches.map((match) => (
              <div
                key={match.id}
                style={{
                  display: "grid",
                  gridTemplateColumns: "2fr 1fr 1fr 1fr auto",
                  gap: 12,
                  padding: 12,
                  background: match.Status === "finished" ? "#2a2a2a" : "#1a1a1a",
                  borderRadius: 4,
                  alignItems: "center",
                }}
              >
                <div>
                  <strong>{match.FighterAName} vs {match.FighterBName}</strong>
                  {match.Status === "finished" && match.WinnerId && (
                    <div style={{ fontSize: "0.85em", color: "#28a745" }}>
                      Winner: {match.WinnerId === "fighterA" ? match.FighterAName : match.FighterBName}
                    </div>
                  )}
                </div>

                <select
                  value={match.MatId}
                  onChange={(e) => updateMatchMat(match.id, e.target.value)}
                  disabled={match.Status === "finished"}
                >
                  <option value="mat1">Mat 1</option>
                  <option value="mat2">Mat 2</option>
                  <option value="mat3">Mat 3</option>
                  <option value="mat4">Mat 4</option>
                </select>

                <select
                  value={match.Status}
                  onChange={(e) => updateMatchStatus(match.id, e.target.value as MatchStatus)}
                >
                  <option value="scheduled">Scheduled</option>
                  <option value="in_progress">In Progress</option>
                  <option value="finished">Finished</option>
                </select>

                <div style={{ fontSize: "0.85em" }}>
                  A: {match.PointsA}p / {match.AdvantagesA}a<br />
                  B: {match.PointsB}p / {match.AdvantagesB}a
                </div>

                <button
                  onClick={() => deleteMatch(match.id)}
                  style={{ background: "#dc3545", color: "white", padding: "8px 12px" }}
                >
                  Delete
                </button>
              </div>
            ))}

            {standaloneMatches.length === 0 && (
              <div style={{ textAlign: "center", padding: 40, color: "#888" }}>
                No standalone matches. Use brackets for tournament matches!
              </div>
            )}
          </div>
        </div>
      )}

      {/* Mat Queues Tab */}
      {activeTab === "queues" && (
        <div>
          <h2 style={{ margin: "0 0 16px 0" }}>Mat Queues</h2>
          <p style={{ color: "#888", marginBottom: 24 }}>
            Drag matches to reorder the queue for each mat. Changes are saved automatically.
          </p>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(350px, 1fr))", gap: 24 }}>
            {["mat1", "mat2", "mat3", "mat4"].map((matId) => {
              // Sort matches by age group (queueOrder only when both have it)
              const matMatches = matches
                .filter((m) => m.MatId === matId && m.Status !== "finished")
                .sort((a, b) => {
                  // Only use queueOrder if BOTH matches have it
                  if (a.queueOrder !== undefined && b.queueOrder !== undefined) {
                    return a.queueOrder - b.queueOrder;
                  }

                  // Otherwise, use age group ordering
                  const bracketA = brackets.find((br) => br.id === a.bracketId);
                  const bracketB = brackets.find((br) => br.id === b.bracketId);
                  const ageOrderA = bracketA ? AGE_GROUP_ORDER.indexOf(bracketA.ageGroup) : 999;
                  const ageOrderB = bracketB ? AGE_GROUP_ORDER.indexOf(bracketB.ageGroup) : 999;
                  if (ageOrderA !== ageOrderB) return ageOrderA - ageOrderB;
                  if (a.bracketId !== b.bracketId) return (a.bracketId || "").localeCompare(b.bracketId || "");
                  const roundA = a.bracketRound ?? a.Round ?? 0;
                  const roundB = b.bracketRound ?? b.Round ?? 0;
                  return roundA - roundB;
                });

              if (matMatches.length === 0) return null;

              return (
                <MatQueuePanel
                  key={matId}
                  matId={matId}
                  matches={matMatches}
                  brackets={brackets}
                  onReorder={reorderMatches}
                  onReset={() => resetQueueOrder(matId)}
                />
              );
            })}
          </div>

          {matches.filter((m) => m.Status !== "finished").length === 0 && (
            <div style={{ textAlign: "center", padding: 40, color: "#888" }}>
              No scheduled matches. Create brackets to add matches!
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function MatQueuePanel({
  matId,
  matches,
  brackets,
  onReorder,
  onReset,
}: {
  matId: string;
  matches: MatchWithId[];
  brackets: BracketWithId[];
  onReorder: (matches: MatchWithId[]) => Promise<void>;
  onReset: () => void;
}) {
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);

  const handleDragStart = (e: React.DragEvent, index: number) => {
    setDraggedIndex(index);
    e.dataTransfer.effectAllowed = "move";
    e.dataTransfer.setData("text/plain", index.toString());
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
    setDragOverIndex(index);
  };

  const handleDragLeave = () => {
    setDragOverIndex(null);
  };

  const handleDrop = async (e: React.DragEvent, dropIndex: number) => {
    e.preventDefault();
    if (draggedIndex === null || draggedIndex === dropIndex) {
      setDraggedIndex(null);
      setDragOverIndex(null);
      return;
    }

    const newQueue = [...matches];
    const [removed] = newQueue.splice(draggedIndex, 1);
    newQueue.splice(dropIndex, 0, removed);

    setDraggedIndex(null);
    setDragOverIndex(null);

    await onReorder(newQueue);
  };

  const handleDragEnd = () => {
    setDraggedIndex(null);
    setDragOverIndex(null);
  };

  const inProgressMatch = matches.find((m) => m.Status === "in_progress");
  const scheduledMatches = matches.filter((m) => m.Status === "scheduled");

  return (
    <div style={{
      background: "#1a1a1a",
      borderRadius: 12,
      overflow: "hidden",
    }}>
      {/* Mat Header */}
      <div style={{
        background: "#0d6efd",
        padding: "12px 16px",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
      }}>
        <div style={{ fontWeight: 700, fontSize: "1.125rem" }}>
          {matId.replace("mat", "Mat ")}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <span style={{ fontSize: "0.875rem", opacity: 0.9 }}>
            {matches.length} matches
          </span>
          <button
            onClick={onReset}
            style={{
              padding: "4px 10px",
              fontSize: "0.75rem",
              background: "rgba(255,255,255,0.2)",
              border: "none",
              borderRadius: 4,
              color: "white",
              cursor: "pointer",
            }}
          >
            Reset Order
          </button>
        </div>
      </div>

      {/* In Progress Match */}
      {inProgressMatch && (
        <div style={{
          padding: "12px 16px",
          background: "#ffc10722",
          borderBottom: "1px solid #333",
        }}>
          <div style={{
            fontSize: "0.625rem",
            fontWeight: 600,
            color: "#ffc107",
            textTransform: "uppercase",
            marginBottom: 4,
          }}>
            In Progress
          </div>
          <div style={{ fontWeight: 600 }}>
            {inProgressMatch.FighterAName} vs {inProgressMatch.FighterBName}
          </div>
        </div>
      )}

      {/* Queue List */}
      <div style={{ padding: 12 }}>
        {scheduledMatches.length === 0 ? (
          <div style={{ textAlign: "center", padding: 20, color: "#666" }}>
            No scheduled matches
          </div>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
            {scheduledMatches.map((match, index) => {
              const bracket = brackets.find((b) => b.id === match.bracketId);

              return (
                <div
                  key={match.id}
                  draggable
                  onDragStart={(e) => handleDragStart(e, index)}
                  onDragOver={(e) => handleDragOver(e, index)}
                  onDragLeave={handleDragLeave}
                  onDrop={(e) => handleDrop(e, index)}
                  onDragEnd={handleDragEnd}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 10,
                    padding: "10px 12px",
                    background: dragOverIndex === index ? "#0d6efd22" : "#2a2a2a",
                    borderRadius: 6,
                    cursor: "grab",
                    opacity: draggedIndex === index ? 0.5 : 1,
                    border: dragOverIndex === index ? "2px dashed #0d6efd" : "2px solid transparent",
                    transition: "background 0.15s, border 0.15s",
                  }}
                >
                  <div style={{
                    width: 24,
                    height: 24,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    background: "#444",
                    borderRadius: 4,
                    fontSize: "0.75rem",
                    fontWeight: 700,
                    color: "#888",
                    flexShrink: 0,
                  }}>
                    {index + 1}
                  </div>
                  <div style={{
                    color: "#555",
                    fontSize: "1rem",
                    flexShrink: 0,
                  }}>
                    ⠿
                  </div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: "0.875rem", fontWeight: 500 }}>
                      {match.FighterAName} <span style={{ color: "#666" }}>vs</span> {match.FighterBName}
                    </div>
                    {bracket && (
                      <div style={{ fontSize: "0.75rem", color: "#666", marginTop: 2 }}>
                        {bracket.name}
                      </div>
                    )}
                  </div>
                  {match.queueOrder !== undefined && (
                    <div style={{
                      fontSize: "0.625rem",
                      color: "#0d6efd",
                      background: "#0d6efd22",
                      padding: "2px 6px",
                      borderRadius: 3,
                      flexShrink: 0,
                    }}>
                      CUSTOM
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
